posts/urls.py
# Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
# Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
# See License.txt in the project root for license information.

from django.urls import path

from . import views

app_name = 'posts'

post_direct_url = 'post-direct/'

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('account-login', views.account_login, name='account-login'),
    path('signup/', views.signup, name='signup'),
    path('create-account/', views.create_account, name='create-account'),
    path('profile/', views.profile, name='profile'),
    path('post-editor/', views.post_editor, name='post-editor'),
    path('post-preview/', views.post_preview, name='post-preview'),
    path('post-preview-display/', views.post_preview_display, name='post-preview-display'),
    path('new-post/', views.new_post, name='new-post'),
    path('author/<str:author_name>/', views.author, name='author'),
    path('post/<str:author_name>/<str:post_title>/', views.post, name='post'),
    path((post_direct_url + '<str:post_id>/'), views.post_direct, name='post-direct'),
    path('api/check-username/', views.api_check_username, name='api-check-username'),
    path('api/get-post-body/', views.api_get_post_body, name='api-get-post-body'),
    path('api/save-post/', views.api_save_post, name='api-save-post'),
    path('api/get-recent-posts/', views.api_get_recent_posts, name='api-get-recent-posts'),
    path('api/check-post-title/', views.api_check_post_title, name='api-check-post-title'),
]

universe/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
# Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
# Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
# See License.txt in the project root for license information.

from django.db import models

from django.contrib.auth.models import User

# Create your models here.


class Posts(models.Model):
    post_id = models.CharField(max_length = 40, null = True)
    title = models.CharField(max_length = 100)
    author_name = models.CharField(max_length = 40)
    author_id = models.CharField(max_length = 40)
    creation_date = models.DateTimeField(auto_now_add=True)
    file_id = models.FileField(upload_to='posts/', max_length=200)

    def __str__(self):
        return self.title


class Custom_User(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    custom_username = models.CharField(max_length=100, null=True, blank=True)
    posts_ids = models.CharField(max_length = 2000, null=True, blank=True)

posts/views.py
# Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
# Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
# See License.txt in the project root for license information.

from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from .models import Posts, Custom_User

import json
from . import helpers
from . import urls


# This function acts as the homepage or '/' route of the website.
def index(request):
    user = request.user
    context = {'user_logged_in':False}

    if request.user.is_authenticated:
        username = user.get_username()
        context = {'username':username, 'user_logged_in':True}

    return render(request, "posts/index.html", context)


# This function is used to display the login page.
def login_page(request):
    return render(request, "posts/login.html")


# This function logs out the user and displays the logout page.
def logout_page(request):
    logout(request)
    context = {'from':"ACCOUNT LOGOUT:", 'message':"LOGGED OUT SUCCESSFULLY!"}
    return render(request, "posts/misc.html", context)


# This function is user to authenticate the user and login the user.
# If authentication is successful, then, the user is redirected to the homepage.
# If the authentication is not successful, then, an invalid credentials page is displayed.
def account_login(request):
    username = request.POST.get('username')
    password = str(request.POST.get('password'))

    user = authenticate(request, username = username, password = password)

    if user is not None:
        login(request, user)
        return HttpResponseRedirect(reverse("posts:home"))
    else:
        context = {'from':"ACCOUNT LOGIN ERROR:", 'message':"INVALID CREDENTIALS!"}
        return render(request, "posts/misc.html", context)


# This function is used to display the signup page.
def signup(request):
    return render(request, "posts/signup.html")


# This function is used to create a new account.
def create_account(request):
    username = str(request.POST.get('username'))
    password = str(request.POST.get('password'))
    email = str(request.POST.get('email'))
    first_name = str(request.POST.get('first_name'))
    last_name = str(request.POST.get('last_name'))
    info = ['Username : ' + username, 'Password : ' + password, 'Email : ' + email, 
    'First Name : ' + first_name, 'Last Name : ' + last_name]

    # Checks for invalid username or password or email field.
    if (username or password or email) == "":
        context = {'from':'NEW ACCOUNT NOT CREATED!', 'message':'Invalid username or password or email', 'info':info}
        return render(request, "posts/misc.html", context)

    # Checks if the username is already taken or not.
    if (username or password) is not None:
        try:
            check_user_exist = User.objects.get(username = username)
            check_user_exist = True
        except User.DoesNotExist:
            check_user_exist = False

        # If the username is not available, then, an error page is shown.
        if check_user_exist is True:
            context = {'from':'NEW ACCOUNT NOT CREATED!', 'message':'Username already taken!', 'info':info}
            return render(request, "posts/misc.html", context)

        # Creates the user with the provided data.
        user = User.objects.create_user(username = username, password = password, email = email,
        first_name = first_name, last_name = last_name)
        user.save()

        # Create the Custom_User for storing the user's posts_ids.
        cu = Custom_User(user = user, custom_username = user.username)
        cu.save()

    context = {'from':'NEW ACCOUNT CREATED!', 'message':'NEW ACCOUNT CREATED!', 'info':info}
    context['new_account_status'] = 'true'
    return render(request, "posts/misc.html", context)


# This function is used to display the user's profile.
def profile(request):
    user = request.user
    user_logged_in = False

    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("posts:home"))

    username = str(user.get_username())
    user_logged_in = True
    full_name = str(user.first_name + ' ' + user.last_name)

    # Used to obtain the recent posts' titles and post links.
    recent_posts, old_posts = helpers.get_recent_posts(user)

    context = {'user_logged_in': user_logged_in, 'username':username, 'author_username':username, 'full_name':full_name, 'email':user.email}
    context['recent_posts'] = recent_posts
    context['message'] = 'false'
    context['recent_posts_status'] = old_posts

    # If a message is supplied with the url (via GET request), then, it is shown on the webpage.
    message = request.GET.get('message')
    if message is not None:
        context['message'] = message

    return render(request, "posts/profile.html", context)


# This function is used to display an author's information.
def author(request, author_name):
    user = request.user
    user_logged_in = False
    if not user.is_authenticated:
        user_logged_in = False
        username = ''
    else:
        user_logged_in = True
        username = str(user.get_username())

    try:
        author = User.objects.get(username = author_name)
    except:
        context = {'from':'Posts', 'message':'Author not found!'}
        return render(request, 'posts/misc.html', context)

    # Used to obtain the recent posts' titles and post links.
    recent_posts, old_posts = helpers.get_recent_posts(author)

    full_name = str(author.first_name + ' ' + author.last_name)
    context = {'user_logged_in': user_logged_in, 'username':username, 'author_username':author.username, 'full_name':full_name, 'email':author.email, 'recent_posts':recent_posts}
    context['message'] = 'false'
    context['recent_posts_status'] = old_posts

    return render(request, "posts/profile.html", context)


# This function is used to display the requested post.
# It takes the author's name and post's title to obtain the proper post.
def post(request, author_name, post_title):
    user = request.user
    user_logged_in = False
    if not user.is_authenticated:
        user_logged_in = False
        username = ''
    else:
        user_logged_in = True
        username = str(user.get_username())

    # Checks if the author's name exists, else, displays an error message.
    try:
        author = User.objects.get(username = author_name)
    except:
        context = {'from':'Posts', 'message':'Author not found!'}
        return render(request, 'posts/misc.html', context)

    # Checks if the requested post exists, else, displays an error message.
    try:
        post = Posts.objects.get(title = post_title, author_name = author_name)
    except:
        context = {'from':'Posts', 'message':'Post not found!'}
        return render(request, 'posts/misc.html', context)

    post_date = post.creation_date

    text = post.file_id.read()
    text = text.decode('utf-8')

    post_link = '/' + urls.post_direct_url + post.post_id

    context = {'username':username, 'post_text':text}
    context['post_title'] = post_title
    context['author_name'] = author_name
    context['post_date'] = post_date
    context['user_logged_in'] = user_logged_in
    context['post_link'] = post_link
    return render(request, 'posts/post.html', context)


# This function is used to display the post, directly by using the post_id.
def post_direct(request, post_id):
    user = request.user
    user_logged_in = False
    if not user.is_authenticated:
        user_logged_in = False
        username = ''
    else:
        user_logged_in = True
        username = str(user.get_username())

    try:
        post = Posts.objects.get(post_id = post_id)
    except:
        context = {'from':'Posts', 'message':'Post not found!'}
        return render(request, 'posts/misc.html', context)

    text = post.file_id.read()
    text = text.decode('utf-8')

    post_link = '/' + urls.post_direct_url + post.post_id

    context = {'username':username, 'post_text':text}
    context['post_title'] = post.title
    context['author_name'] = post.author_name
    context['post_date'] = post.creation_date
    context['user_logged_in'] = user_logged_in
    context['post_link'] = post_link
    return render(request, 'posts/post.html', context)


# This function is used to display the post editor (post manager) page.
def post_editor(request):
    user = request.user
    user_logged_in = False

    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("posts:home"))

    username = str(user.get_username())

    user_logged_in = True
    context = {'user_logged_in':user_logged_in, 'username':username}

    # Used to obtain the titles and post_id(s) of the user's all submitted posts.
    previous_posts, old_posts = helpers.get_all_previous_posts(user)

    context['old_posts'] = old_posts
    context['previous_posts'] = previous_posts

    return render(request, 'posts/post_editor.html', context)


# This function is used to process the new posts created by the users.
# It generates the post preview link, post_id.
@csrf_exempt
def post_preview(request):
    user = request.user

    if not user.is_authenticated:
        return HttpResponseRedirect(reverse("posts:home"))

    try:
        send_type = str(request.POST.get('send-type'))

        print('\n\n\n\nTESTINGS')
        print('send_type = ' + send_type)
        print('FILES : ' + str(request.FILES))

        post_title = request.POST.get('post-title')

        # Checks if the title is available or not.
        check_post_exist = False
        try:
            author_name = str(user.get_username())

posts/templates/posts/index.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends "posts/base.html" %}

{% load static %}

{% block title %}
UNIVERSE HOME
{% endblock %}

{% block extraHead %}
<link rel="stylesheet" href="{% static 'posts/CSS/navbar.css' %}"/>
<script src="{% static 'posts/javascript/navbarUI.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/CSS/index.css' %}"/>
<script src="{% static 'posts/javascript/index.js' %}"></script>
{% endblock %}

{% block body %}

<nav class="top-navbar">
    <a class="nav-list-item-left" id="logo" href="{% url 'posts:home' %}">UNIVERSE</a>

    {% if user_logged_in %}
        <span class="nav-list-item-left" id="greet-user">WELCOME, {{ username }} !</span>
    {% endif %}

    <button class="nav-list-item-right" id="user-icon">
        <img id="user-icon-img" src="{% static 'posts/images/user.svg' %}" width="50px" height="50px"/>
    </button>
</nav>

<div class="dropdown-toggle-list" id="user-dropdown">
    {% if user_logged_in %}
        <a class="dropdown-content" href="{% url 'posts:profile' %}">PROFILE</a>
        <a class="dropdown-content" href="{% url 'posts:post-editor' %}">MANAGE POSTS</a>
        <a class="dropdown-content" href="{% url 'posts:logout' %}">LOGOUT</a>
    {% else %}
        <a class="dropdown-content" href="{% url 'posts:signup' %}">CREATE ACCOUNT</a>
        <a class="dropdown-content" href="{% url 'posts:login' %}">LOGIN</a>
    {% endif %}
</div>

<div class="surface">
    <div class="site-information-container">
        <p class="site-information">Create your stories and share them with the world!</p>
        <p class="site-information">SHARE YOUR KNOWLEDGE!</p>
        <p class="site-information">Spread the word!</p>
    </div>

    <hr class="separator">

    <div id="recent-posts">
    </div>
</div>

<br><br><br><br><br><br><br><br>

<div class="footer">
    <p>This website is created by <span id="creator">OM SANTOSHKUMAR MASNE</span>.</p>
    <p>This is a project website for edX's course "Web programming with python and javascript".</p>
    <p>This is an web-app for Posts sharing - UNIVERSE.</p>
</div>

{% endblock %}

posts/templates/posts/login.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends "posts/base.html" %}

{% load static %}

{% block title %}
LOGIN
{% endblock %}

{% block extraHead %}
<link rel="stylesheet" href="{% static 'posts/CSS/signup.css' %}" />
{% endblock %}

{% block body %}

<div class="signup">
    <p class="signup-head">
        ACCOUNT LOGIN!
    </p>
    <br>
    <br>

    <form id="signup-form" action="{% url 'posts:account-login' %}" method="POST">
        {% csrf_token %}

        <h2 class="form-input-head">USERNAME:</h2>
        <input class="form-input" type="text" name="username" placeholder="ENTER USERNAME" required />
        <br>
        <br>
        <hr class="form-item-break">

        <h2 class="form-input-head">PASSWORD:</h2>
        <input class="form-input" type="password" name="password" placeholder="ENTER PASSWORD" required />
        <br>
        <br>
        <hr class="form-item-break">

        <br>
        <br>

        <div class="go-to-home">
            <a href="{% url 'posts:home' %}">CANCEL and goto HomePage!</a>
        </div>

        <div class="form-submit" id="form-submit-div">
            <button class="form-submit-button" type="submit">LOGIN!</button>
        </div>
    </form>
</div>

{% endblock %}

posts/templates/posts/post.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends 'posts/base.html' %}

{% load static %}

{% block title %}
Post
{% endblock %}

{% block extraHead %}
<!--
    rotating shapes outlines background!
-->
<link rel="stylesheet" href="{% static 'posts/CSS/navbar.css' %}" />
<script src="{% static 'posts/javascript/navbarUI.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/CSS/post.css' %}" />
{% endblock %}

{% block body %}

<nav class="top-navbar">
    <a class="nav-list-item-left" id="logo" href="{% url 'posts:home' %}">UNIVERSE</a>

    {% if user_logged_in %}
        <span class="nav-list-item-left" id="greet-user">WELCOME, {{ username }} !</span>
    {% endif %}

    <button class="nav-list-item-right" id="user-icon">
        <img id="user-icon-img" src="{% static 'posts/images/user.svg' %}" width="50px" height="50px"/>
    </button>
</nav>

<div class="dropdown-toggle-list" id="user-dropdown">
    {% if user_logged_in %}
        <a class="dropdown-content" href="{% url 'posts:profile' %}">PROFILE</a>
        <a class="dropdown-content" href="{% url 'posts:post-editor' %}">MANAGE POSTS</a>
        <a class="dropdown-content" href="{% url 'posts:logout' %}">LOGOUT</a>
    {% else %}
        <a class="dropdown-content" href="{% url 'posts:signup' %}">CREATE ACCOUNT</a>
        <a class="dropdown-content" href="{% url 'posts:login' %}">LOGIN</a>
    {% endif %}
</div>

<div id="post-info">
    <div id="post-title">{{ post_title }}</div>
    <div id="author-info">Author : {{ author_name }}</div>
    <div id="post-data">Date: {{ post_date }}</div>
</div>

<hr id="post-body-separator">

<div id="post-body">{{ post_text |safe }}</div>

<hr id="post-body-separator">

<div id="permanent-link">
    <p>Share this post with this permanent link:</p>
    <a href="{{ post_link }}">Permanent Link</a>
</div>

{% endblock %}

posts/templates/posts/post_editor.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends "posts/base.html" %}

{% load static %}

{% block title %}
UNIVERSE POST EDITOR
{% endblock %}

{% block extraHead %}
<!--
    rotating shapes outlines background!
-->
<link rel="stylesheet" href="{% static 'posts/CSS/navbar.css' %}" />
<script src="{% static 'posts/javascript/navbarUI.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/CSS/post_editor.css' %}" />
<script src="{% static 'posts/javascript/post_editor.js' %}"></script>

<script src="{% static 'posts/medium-editor/js/medium-editor.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/medium-editor/css/medium-editor.css' %}">
<link rel="stylesheet" href="{% static 'posts/medium-editor/css/themes/default.css' %}">
{% endblock %}

{% block body %}

<nav class="top-navbar">
    <a class="nav-list-item-left" id="logo" href="{% url 'posts:home' %}">UNIVERSE</a>

    {% if user_logged_in %}
        <span class="nav-list-item-left" id="greet-user">WELCOME, {{ username }} !</span>
        <input id="username" value="{{ username }}" hidden>
    {% endif %}

    <button class="nav-list-item-right" id="user-icon">
        <img id="user-icon-img" src="{% static 'posts/images/user.svg' %}" width="50px" height="50px"/>
    </button>
</nav>

<div class="dropdown-toggle-list" id="user-dropdown">
    {% if user_logged_in %}
        <a class="dropdown-content" href="{% url 'posts:profile' %}">PROFILE</a>
        <a class="dropdown-content" href="{% url 'posts:post-editor' %}">MANAGE POSTS</a>
        <a class="dropdown-content" href="{% url 'posts:logout' %}">LOGOUT</a>
    {% else %}
        <a class="dropdown-content" href="{% url 'posts:signup' %}">CREATE ACCOUNT</a>
        <a class="dropdown-content" href="{% url 'posts:login' %}">LOGIN</a>
    {% endif %}
</div>

<div class="page-head" id="page-head-id">
    <h1 class="page-title-head">Create a new post or edit an old one!</h1>

    <p class="page-information">Select the new post button to create a new post.</p>
    <p class="page-information">OR</p>
    <p class="page-information">Choose to edit your old post by selecting it from the dropdown list.</p>

    <div class="page-option-chooser">
        <button class="page-head-btn" id="create-new-post-btn">CREATE NEW POST!</button>
        <br>
        <br>
        <div class="old-posts-container">
            {% if old_posts %}
                <select class="old-posts" id="old-posts-selection">
                    {% for post_title, post_id in previous_posts %}
                        <option value="{{ post_title }}" data-id="{{ post_id }}">{{ post_title }}</option>
                    {% endfor %}
                </select>
                <button class="page-head-btn" id="post-edit-btn">EDIT NOW!</button>
            {% else %}
                <span>You have no previous posts!</span>
                <button class="page-head-btn-disabled" id="post-edit-btn" disabled>EDIT NOW!</button>
            {% endif %}
        </div>
    </div>
</div>

<div id="new-post-surface">
    <h1 class="page-title-head">Create a new post!</h1>
    <p class="page-information">Choose a title:</p>
    <input id="new-post-title-input" placeholder="Choose a title for your post!">
    <button id="submit-new-post-btn" class="btn-style-post">Preview and POST!</button>
    <br>
    <br>
    <button class="btn-style-2" id="upload-post">Upload your post</button>
    <input id="file-upload-input" name="file-upload-input" type="file" accept=".txt,.md" hidden>
    <p class="page-information-divider">OR</p>
    <button class="btn-style-2" id="write-post-here">Write it here.</button>
    <br>
    <br>

    <div id="file-to-upload-name-container">
        <span>Selected file : <span id="selected-file-name-display"></span></span>
    </div>

    <br>

    <div class="post-editor" id="new-post-creator">
        <div id="new-post-textarea" class="editable"></div>
    </div>
</div>

<div id="post-editor-container">
    <h1 class="page-title-head">Edit old post!</h1>
    <p class="page-information">You can edit the title and the post body:</p>
    <input id="edit-post-title-input">
    <button id="save-post-btn" class="btn-style-post">SAVE POST!</button>
    <br>
    <br>

    <div class="post-editor" id="old-post-editor">
        <div id="edit-post-textarea" class="editable"></div>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_preview.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends "posts/base.html" %}

{% load static %}

{% block title %}
UNIVERSE POST EDITOR
{% endblock %}

{% block extraHead %}
<!--
    rotating shapes outlines background!
-->
<link rel="stylesheet" href="{% static 'posts/CSS/navbar.css' %}" />
<script src="{% static 'posts/javascript/navbarUI.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/CSS/post_preview.css' %}" />
<script src="{% static 'posts/javascript/post_preview.js' %}"></script>
{% endblock %}

{% block body %}

<nav class="top-navbar">
    <a class="nav-list-item-left" id="logo" href="{% url 'posts:home' %}">UNIVERSE</a>

    {% if user_logged_in %}
        <span class="nav-list-item-left" id="greet-user">WELCOME, {{ username }} !</span>
    {% endif %}

    <button class="nav-list-item-right" id="user-icon">
        <img id="user-icon-img" src="{% static 'posts/images/user.svg' %}" width="50px" height="50px"/>
    </button>
</nav>

<div class="dropdown-toggle-list" id="user-dropdown">
    {% if user_logged_in %}
        <a class="dropdown-content" href="{% url 'posts:profile' %}">PROFILE</a>
        <a class="dropdown-content" href="{% url 'posts:post-editor' %}">MANAGE POSTS</a>
        <a class="dropdown-content" href="{% url 'posts:logout' %}">LOGOUT</a>
    {% else %}
        <a class="dropdown-content" href="{% url 'posts:signup' %}">CREATE ACCOUNT</a>
        <a class="dropdown-content" href="{% url 'posts:login' %}">LOGIN</a>
    {% endif %}
</div>

<form id="decision-form">
    {% csrf_token %}
</form>

<hr>

<div class="decide-post">
    <input id="post-id" value="{{ post_id }}" hidden>
    <button id="approve-post">POST NOW!</button>
    <button id="change-post">CANCEL</button>
    <br>
    <p id="post-preview-note">NOTE: This preview is not properly formated. Actual post may look different!</p>
</div>

<hr>

<div class="post-preview">
    <div id="post-title-preview">
        <input id="post-title-value" value="{{ post_title }}" hidden>
        <p>{{ post_title }}</p>
        <p class="post-information-part">POST AND AUTHOR INFORMATION</p>
    </div>
    
    <iframe src="{{ post_preview_link }}" id="post-preview-frame"></iframe>
</div>

{% endblock %}

posts/templates/posts/profile.html
<!--
    Copyright (C) 2019 OM SANTOSHKUMAR MASNE. All Rights Reserved.
    Licensed under the GNU Affero General Public License v3.0 only (AGPL-3.0-only) license.
    See License.txt in the project root for license information.
-->

{% extends "posts/base.html" %}

{% load static %}

{% block title %}
UNIVERSE PROFILE
{% endblock %}

{% block extraHead %}
<!--
    rotating shapes outlines background!
-->
<link rel="stylesheet" href="{% static 'posts/CSS/navbar.css' %}" />
<script src="{% static 'posts/javascript/navbarUI.js' %}"></script>
<link rel="stylesheet" href="{% static 'posts/CSS/profile.css' %}" />
<script src="{% static 'posts/javascript/profile.js' %}"></script>
{% endblock %}

{% block body %}

<nav class="top-navbar">
    <a class="nav-list-item-left" id="logo" href="{% url 'posts:home' %}">UNIVERSE</a>

    {% if user_logged_in %}
        <span class="nav-list-item-left" id="greet-user">WELCOME, {{ username }} !</span>
    {% endif %}

    <button class="nav-list-item-right" id="user-icon">
        <img id="user-icon-img" src="{% static 'posts/images/user.svg' %}" width="50px" height="50px"/>
    </button>
</nav>

<div class="dropdown-toggle-list" id="user-dropdown">
    {% if user_logged_in %}
        <a class="dropdown-content" href="{% url 'posts:profile' %}">PROFILE</a>
        <a class="dropdown-content" href="{% url 'posts:post-editor' %}">MANAGE POSTS</a>
        <a class="dropdown-content" href="{% url 'posts:logout' %}">LOGOUT</a>
    {% else %}
        <a class="dropdown-content" href="{% url 'posts:signup' %}">CREATE ACCOUNT</a>
        <a class="dropdown-content" href="{% url 'posts:login' %}">LOGIN</a>
    {% endif %}
</div>

<div id="message-container">
    <input id="message" value="{{ message }}" hidden>
</div>

<div class="surface">
    <h1 class="profile-head">USER PROFILE:</h1>

    <hr class="profile-section-divider">

    <div class="section-head">User information:</div>

    <div id="user-info">
        <span class="user-info-container">
            Username : 
            <span class="user-info-display">{{ author_username }} </span>.
        </span>
        <br>
        <span class="user-info-container">
            Name : 
            <span class="user-info-display">{{ full_name }} </span>.
        </span>
        <br>
        <span class="user-info-container">
            Email : 
            <span class="user-info-display">{{ email }}</span>
        </span>
    </div>

    <hr class="profile-section-divider">

    <div class="recent-posts-container">
        <div class="section-head">Your recent posts:</div>
        {% if recent_posts_status %}
            {% for post_title, post_link in recent_posts %}
            <a href="{{ post_link }}">
                <div class="recent-posts">
                    {{ forloop.counter }} . {{ post_title }}.
                </div>
            </a>
            {% endfor %}
        {% else %}
        <div class="no-recent-posts">
            You have not created any posts yet!
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}